### ISSUE TITLE
some questions about training stage

### ISSUE THREAD

**Issue by Krapnuh** [siyuhuang/QuantArt#2]
Hi!

Thanks for great paper and your implementation.

I want to try reproduce your code and train a custom model.

First, on the training stage 1, 'vqgan_wikiart.yaml' uses the pretrained model 'vqgan_imagenet_f16_1024.ckpt'  and wikiart dataset for training wikiart style auto-encoder. Does it mean fine-tuning the imagenet auto-encoder with the wikiart(or any) dataset?

Moreover, on the training stage 2, I cannot find style-visual fidelity trade-off parameter(as described figure 3. of paper) alpha and beta on your code.
I cannot find the upper side of (c) Inference stage of figure 3, therefore I think it needs an implementation, or you're only considering visual fidelity.
If I'm wrong, I'd appreciate if you could tell me where that parameters are or your opinion.

**Comment by siyuhuang** [comment]
Hi @Krapnuh , thank for your interest in our work!

 - Yes, we finetuned the VQGAN autoencoder on Wikiart dataset to get `vqgan_wikiart_f16_1024.ckpt`
 - We haven't included the alpha-beta parameters in the repo. We only included the model for the best visual fidelity, since it's the main difference of this work and previous style transfer works.

**Comment by Krapnuh** [comment]
Thank you so much!! :)
